New content for terms of use
SkillsFundingAgency/das-apim-developer-web pull request #89
Opened 2024-11-21 12:01 UTC by LACrossley

2024-11-21 13:16 UTC, balaji-j submitted a review, later dismissed

2024-11-21 13:45 UTC, killij requested changes, later dismissed

2024-11-21 13:45 UTC, killij commented on src/SFA.DAS.Apim.Developer.Web/Views/ThirdPartyAccounts/TermsConditions.cshtml
> +            <li>provides accurate and complete information</li>
Copy doc is different here

2024-11-28 15:16 UTC, LACrossley commented on src/SFA.DAS.Apim.Developer.Web/Views/ThirdPartyAccounts/TermsConditions.cshtml
> +            <li>provides accurate and complete information</li>
Ah yes! I spoke with Chris Lightfoot about this section. The copy doc isn't grammatically correct here. We agreed this change would be better.

2024-11-28 15:19 UTC, dashton82 approved these changes, later dismissed

2024-12-06 10:33 UTC, killij approved these changes

2024-12-06 10:34 UTC, merged